on: push

permissions:
  id-token: write # Needed to federate with octo-sts
  
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate with octo-sts
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        
      - uses: octo-sts/action@main
        id: octo-sts
        with:
          scope: chris-octo-sts-test/test-octo-sts
          identity: foo
          domain: octo-sts.stacklok.dev
          
      - env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh issue list
