on: push

permissions:
  id-token: write # Needed to federate with octo-sts
  
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate with octo-sts
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: chris-octo-sts-test/test-octo-sts
          identity: foo
          
      - env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh issue list
